exports.ONBOARDING_FORM_STATUS = "status2"
exports.MONDAY_BOARDS_FORM_STATUS = "status4"
exports.GOOGLE_DRIVE_FORM_STATUS = "status7"
exports.SLACK_FORM_STATUS = "status1"
exports.MONDAY_DB_FORM_STATUS = "status9"
exports.TOGGL_FORM_STATUS = "status42"
exports.FRAMEIO_FORM_STATUS = "status8"
exports.START_FORM_STATUS = "status"
